import pandas as pd
import io
from datetime import datetime, timedelta
from fastapi import APIRouter, UploadFile, HTTPException, File
from concurrent.futures import ThreadPoolExecutor, as_completed

from app.controller.Concepto import PostConcepto, GetLastID as idConcepto, GetConcepto as GetAllConceptos
from app.controller.Secuencia import PostSecuencia, GetLastID as idSecuencia, GetSecuencia as GetAllSecuencias
from app.controller.Movimiento import PostMovimiento
from app.schemas.SchemaConcepto import ConceptoCreateModel
from app.schemas.SchemaSecuencia import SecuenciaCreateModel
from app.schemas.SchemaMovimiento import MovimientoCreateModel

router = APIRouter()

def dias_del_mes(mes, anio):
    return [datetime(anio, mes, dia) for dia in range(1, 32)]

def clean_dataframe(df):
    df[df.columns[0]] = df[df.columns[0]].fillna(method='ffill')
    df = df.dropna(axis=1, how='all')
    df = df.loc[:, ~(df.columns.str.contains('Unnamed') & df.isna().all())]
    return df

def extract_column_data(df, column_name):
    return df[column_name].dropna().unique().tolist()

def process_secuencia_item(item):
    secuencia_data = SecuenciaCreateModel(descripcion=str(item))
    try:
        PostSecuencia.crear_secuencia(secuencia_data)
        return idSecuencia.LastID()
    except HTTPException as e:
        print("Error en process_secuencia_item:", e)
    return None

def process_concepto_item(item):
    if item != 'FECHA':
        concepto_data = ConceptoCreateModel(nombre=item)
        try:
            PostConcepto.crear_concepto(concepto_data)
            return item, idConcepto.LastID()
        except HTTPException as e:
            print("Error en process_concepto_item:", e)
    return item, None

def process_movimiento_item(id_concepto, id_secuencia, value, date):
    movimiento_data = MovimientoCreateModel(id_concepto=id_concepto, id_secuencia=id_secuencia, valor=value, fecha=date)
    try:
        PostMovimiento.crear_movimiento(movimiento_data)
        return "datos insertados con exito"
    except HTTPException as e:
        print("Error en process_movimiento_item:", e)

def obtener_mes_y_anio(fecha_str):
    fecha = datetime.strptime(fecha_str, '%Y-%m-%d')
    return fecha.month, fecha.year

@router.post("/PostCargarPlanMinero/")
async def cargar_datos_desde_excel(fecha: str, file: UploadFile = File(...)):
    if not file.filename.endswith('.xlsx'):
        raise HTTPException(status_code=400, detail="El archivo no es un archivo .xlsx válido.")

    try:
        contents = await file.read()
        data = io.BytesIO(contents)
        df = pd.read_excel(data, sheet_name='DETALLE FINAL DIARIO', engine='openpyxl')
        df = clean_dataframe(df)

        mes, anio = obtener_mes_y_anio(fecha)

        secuencia = extract_column_data(df, df.columns[0])
        conceptos = extract_column_data(df, df.columns[1])

        with ThreadPoolExecutor() as executor:
            secuencias_futures = {executor.submit(process_secuencia_item, item): item for item in secuencia}
            conceptos_futures = {executor.submit(process_concepto_item, item): item for item in conceptos}

            id_secuencias = {item: future.result() for future, item in secuencias_futures.items() if future.result() is not None}
            id_conceptos = {item: future.result()[1] for future, item in conceptos_futures.items() if future.result()[1] is not None}

        secuencia_guardados = GetAllSecuencias.listar_secuencia()
        conceptos_guardados = GetAllConceptos.listar_conceptos()

        with ThreadPoolExecutor() as executor:
            for idx, row in df.iterrows():
                secuencia_excel = row.iloc[0]
                if secuencia_excel in id_secuencias:
                    id_secuencia = id_secuencias[secuencia_excel]
                    concepto_excel = row.iloc[1]
                    if concepto_excel in id_conceptos:
                        id_concepto = id_conceptos[concepto_excel]
                        row_data = row[2:33]
                        numeric_data = pd.to_numeric(row_data, errors='coerce')
                        for dia, value in zip(dias_del_mes(mes, anio), numeric_data):
                            if pd.notna(value):
                                executor.submit(process_movimiento_item, id_concepto, id_secuencia, value, dia)

    except Exception as e:
        print("Excepción:", str(e))
        raise HTTPException(status_code=500, detail=f"Error al procesar el archivo Excel: {str(e)}")

